export const categories = [
  {
    id: "animals",
    name: "Animals",
    icon: "/images/icons/animals.svg",
    color: "peach",
    words: [
      ["Bat", "🦇"],
      ["Dolphin", "🐬"],
      ["Kangaroo", "🦘"],
      ["Kitten", "🐱"],
      ["Lion", "🦁"],
      ["Panda", "🐼"],
      ["Parrot", "🦜"],
      ["Penguin", "🐧"],
      ["Puppy", "🐶"],
      ["Rabbit", "🐰"],
      ["Shark", "🦈"],
      ["Snail", "🐌"],
      ["Whale", "🐳"],
    ],
  },
  {
    id: "body-and-face",
    name: "Body and Face",
    icon: "/images/icons/body-and-face.svg",
    color: "lilac",
    words: [
      ["Beard", "/images/words/body-and-face/beard.svg"],
      ["Moustache", "/images/words/body-and-face/moustache.svg"],
      ["Blonde", "/images/words/body-and-face/blonde.svg"],
      ["Curly", "/images/words/body-and-face/curly.svg"],
      ["Fair", "/images/words/body-and-face/fair.svg"],
      ["Fat", "/images/words/body-and-face/fat.svg"],
      ["Neck", "/images/words/body-and-face/neck.svg"],
      ["Shoulder", "/images/words/body-and-face/shoulder.svg"],
      ["Stomach", "/images/words/body-and-face/stomach.svg"],
      ["Thin", "/images/words/body-and-face/thin.svg"],
      ["Tooth", "/images/words/body-and-face/tooth.svg"],
      ["Teeth", "/images/words/body-and-face/teeth.svg"],
      ["Tongue", "/images/words/body-and-face/tongue.svg"],
    ],
  },
  {
    id: "food-and-drink",
    name: "Food and Drink",
    icon: "/images/icons/food-and-drink.svg",
    color: "pink",
    words: [
      ["Bottle", "/images/words/food-and-drink/bottle.svg"],
      ["Bowl", "/images/words/food-and-drink/bowl.svg"],
      ["Cup", "/images/words/food-and-drink/cup.svg"],
      ["Glass", "/images/words/food-and-drink/glass.svg"],
      ["Milkshake", "/images/words/food-and-drink/milkshake.svg"],
      ["Noodles", "/images/words/food-and-drink/noodles.svg"],
      ["Pancake", "/images/words/food-and-drink/pancake.svg"],
      ["Pasta", "/images/words/food-and-drink/pasta.svg"],
      ["Picnic", "/images/words/food-and-drink/picnic.svg"],
      ["Plate", "/images/words/food-and-drink/plate.svg"],
      ["Sauce", "/images/words/food-and-drink/sauce.svg"],
      ["Soup", "/images/words/food-and-drink/soup.svg"],
      ["Vegetable", "/images/words/food-and-drink/vegetable.svg"],
    ],
  },
  {
    id: "home-and-environment",
    name: "Home and Environment",
    icon: "/images/icons/home-and-environment.svg",
    color: "green",
    words: [
      ["Address", "/images/words/home-and-environment/address.svg"],
      ["Balcony", "/images/words/home-and-environment/balcony.svg"],
      ["Basement", "/images/words/home-and-environment/basement.svg"],
      ["Blanket", "/images/words/home-and-environment/blanket.svg"],
      ["Downstairs", "/images/words/home-and-environment/downstairs.svg"],
      ["Elevator", "/images/words/home-and-environment/elevator.svg"],
      ["Lift", "/images/words/home-and-environment/lift.svg"],
      ["Floor", "/images/words/home-and-environment/floor.svg"],
      ["Internet", "/images/words/home-and-environment/internet.svg"],
      ["Roof", "/images/words/home-and-environment/roof.svg"],
      ["Stairs", "/images/words/home-and-environment/stairs.svg"],
      ["Upstairs", "/images/words/home-and-environment/upstairs.svg"],
    ],
  },
  {
    id: "places-and-travel",
    name: "Places and Travel",
    icon: "/images/icons/places-and-travel.svg",
    color: "blue",
    words: [
      ["Building", "/images/words/places-and-travel/building.svg"],
      ["Café", "/images/words/places-and-travel/cafe.svg"],
      ["Car park", "/images/words/places-and-travel/car-park.svg"],
      ["Cinema", "/images/words/places-and-travel/cinema.svg"],
      ["Circus", "/images/words/places-and-travel/circus.svg"],
      ["Farm", "/images/words/places-and-travel/farm.svg"],
      ["Hospital", "/images/words/places-and-travel/hospital.svg"],
      ["Library", "/images/words/places-and-travel/library.svg"],
      ["Market", "/images/words/places-and-travel/market.svg"],
      ["Shopping center", "/images/words/places-and-travel/shopping-center.svg"],
      ["Station", "/images/words/places-and-travel/station.svg"],
      ["Swimming pool", "/images/words/home-and-environment/pool.svg"],
      ["Bank", "/images/words/places-and-travel/bank.svg"],
    ],
  },
  {
    id: "sports-and-leisure",
    name: "Sports and Leisure",
    icon: "/images/icons/sports-and-leisure.svg",
    color: "yellow",
    words: [
      ["Band", "🎸"],
      ["Sailing", "⛵"],
      ["Comic book", "📖"],
      ["Fishing", "🎣"],
      ["Film", "🎬"],
      ["Movie", "🎬"],
      ["Goal", "🥅"],
      ["Holiday", "🏖️"],
      ["Ice skates", "⛸️"],
      ["Party", "🎉"],
      ["Present", "🎁"],
      ["Roller skates", "🛼"],
      ["Ticket", "🎟️"],
      ["Videoing", "📹"],
      ["Pirate", "🏴‍☠️"],
    ],
  },
].map((category) => ({
  ...category,
  words: category.words.map((entry) => {
    const [word, picture] = Array.isArray(entry) ? entry : [null, entry.picture];
    const answers = Array.isArray(entry) ? [word.toLowerCase()] : entry.answers;

    return {
      word: answers[0],
      answers,
      picture,
      category: category.name.toUpperCase(),
      color: category.color,
    };
  }),
}));
