export const categories = [
  {
    id: "animals",
    name: "Animals",
    icon: "/images/icons/animals.svg",
    color: "peach",
    words: [
      ["Bat", "🦇"],
      ["Dolphin", "🐬"],
      ["Kangaroo", "🦘"],
      ["Kitten", "🐱"],
      ["Lion", "🦁"],
      ["Panda", "🐼"],
      ["Parrot", "🦜"],
      ["Penguin", "🐧"],
      ["Puppy", "🐶"],
      ["Rabbit", "🐰"],
      ["Shark", "🦈"],
      ["Snail", "🐌"],
      ["Whale", "🐳"],
    ],
  },
  {
    id: "body-and-face",
    name: "Body and Face",
    icon: "/images/icons/body-and-face.svg",
    color: "lilac",
    words: [
      ["Beard", "/images/words/body-and-face/beard.svg"],
      ["Blonde", "/images/words/body-and-face/blonde.svg"],
      ["Curly", "/images/words/body-and-face/curly.svg"],
      ["Fair", "/images/words/body-and-face/fair.svg"],
      ["Fat", "/images/words/body-and-face/fat.svg"],
      ["Neck", "/images/words/body-and-face/neck.svg"],
      ["Shoulder", "/images/words/body-and-face/shoulder.svg"],
      ["Stomach", "/images/words/body-and-face/stomach.svg"],
      ["Thin", "/images/words/body-and-face/thin.svg"],
      ["Tooth", "/images/words/body-and-face/tooth.svg"],
      ["Teeth", "/images/words/body-and-face/teeth.svg"],
      ["Tongue", "/images/words/body-and-face/tongue.svg"],
    ],
  },
  {
    id: "food-and-drink",
    name: "Food and Drink",
    icon: "/images/icons/food-and-drink.svg",
    color: "pink",
    words: [
      ["Bottle", "🍼"],
      ["Bowl", "🥣"],
      ["Cup", "☕"],
      ["Glass", "🥛"],
      ["Milkshake", "🥤"],
      ["Noodles", "🍜"],
      ["Pancake", "🥞"],
      ["Pasta", "🍝"],
      ["Picnic", "🧺"],
      ["Plate", "🍽️"],
      ["Sauce", "🫙"],
      ["Soup", "🍲"],
      ["Vegetable", "🥕"],
    ],
  },
  {
    id: "home-and-environment",
    name: "Home and Environment",
    icon: "/images/icons/home-and-environment.svg",
    color: "green",
    words: [
      ["Address", "📮"],
      ["Balcony", "🏢"],
      ["Basement", "🪜"],
      ["Blanket", "🛏️"],
      ["Downstairs", "⬇️"],
      ["Elevator", "🛗"],
      ["Lift", "🛗"],
      ["Floor", "🪵"],
      ["Internet", "🌐"],
      ["Roof", "🏠"],
      ["Stairs", "🪜"],
      ["Upstairs", "⬆️"],
    ],
  },
  {
    id: "places-and-travel",
    name: "Places and Travel",
    icon: "/images/icons/places-and-travel.svg",
    color: "blue",
    words: [
      ["Building", "🏢"],
      ["Café", "☕"],
      ["Car park", "🅿️"],
      ["Cinema", "🎬"],
      ["Circus", "🎪"],
      ["Farm", "🚜"],
      ["Hospital", "🏥"],
      ["Library", "📚"],
      ["Market", "🛍️"],
      ["Shopping centre", "🏬"],
      ["Station", "🚉"],
      ["Swimming pool", "🏊"],
    ],
  },
  {
    id: "sports-and-leisure",
    name: "Sports and Leisure",
    icon: "/images/icons/sports-and-leisure.svg",
    color: "yellow",
    words: [
      ["Band", "🎸"],
      ["CD", "💿"],
      ["Comic book", "📖"],
      ["DVD", "📀"],
      ["Film", "🎬"],
      ["Movie", "🎬"],
      ["Goal", "🥅"],
      ["Holiday", "🏖️"],
      ["Ice skates", "⛸️"],
      ["Party", "🎉"],
      ["Present", "🎁"],
      ["Roller skates", "🛼"],
      ["Ticket", "🎟️"],
    ],
  },
].map((category) => ({
  ...category,
  words: category.words.map((entry) => {
    const [word, picture] = Array.isArray(entry) ? entry : [null, entry.picture];
    const answers = Array.isArray(entry) ? [word.toLowerCase()] : entry.answers;

    return {
      word: answers[0],
      answers,
      picture,
      category: category.name.toUpperCase(),
      color: category.color,
    };
  }),
}));
